services:
  roscore:
    image: ros:noetic-ros-core
    container_name: roscore
    command: roscore
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
    volumes:
      - ./media/group7/USB-ESD:/storage

  camera:
    build:
      context: .
      dockerfile: camera_ws/Dockerfile
    container_name: camera
    image: arm64v8/ros:noetic-ros-base
    command: >
      bash -c "sleep 3 &&
      source /opt/ros/noetic/setup.bash && 
      roslaunch usb_cam camera.launch"
    devices:
      - "/dev/video0:/dev/video0" # IMPORTANT: Make sure this device is correct
    depends_on:
      - roscore
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
    volumes:
      - ./camera_ws/launch:/opt/ros/noetic/share/usb_cam/launch

  camera_stereo:
    build:
      context: .
      dockerfile: camera_stereo_ws/Dockerfile # Points to the new Dockerfile
    container_name: camera_stereo
    network_mode: host
    privileged: true
    restart: unless-stopped
    # Use the correct package name and launch file
    command: bash -c "sleep 3 && roslaunch /etc/ros/stereo_bringup.launch"
    depends_on:
      - roscore
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
    # Mount your local config directory into the container
    volumes:
      - ./camera_stereo_ws/config:/root/calib
    # Add device access for cameras
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"

  camera_mono:
    build:
      context: ./camera_mono_ws
      dockerfile: Dockerfile # Points to the new Dockerfile
    container_name: camera_mono
    network_mode: host
    privileged: true
    restart: unless-stopped
    # Use the correct package name and launch file
    command: bash -c "sleep 3 && roslaunch /etc/ros/camera_bringup.launch"
    depends_on:
      - roscore
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
    # Mount your local config directory into the container
    volumes:
      - ./camera_mono_ws/config:/root/calib
    # Add device access for cameras
    devices:
      - "/dev/video0:/dev/video0"

  imu_node:
    build: ./imu_ws
    container_name: imu_node
    restart: unless-stopped
    privileged: true
    depends_on:
      - roscore
    network_mode: host
    #command: bash -c "sleep 3 && roslaunch /launches/icm20948.launch"
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    group_add:
      - "i2c"
    volumes:
      - ./imu_ws/ros_icm20948/launches:/opt/ros/noetic/share/imu/launch

  mavros:
    build:
      context: ./mavros_ws
      dockerfile: Dockerfile
    container_name: mavros
    depends_on:
      - roscore
    network_mode: host
    volumes:
      - /home/group7/ros_bags:/root/ros_bags
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"   # map Pixhawk serial into container
    command: ["roslaunch", "mavros", "apm.launch", "fcu_url:=/dev/ttyACM0:115200"]
#      - "/dev/ttyAMA10:/dev/ttyAMA10"   # map Pixhawk serial into container
#    command: ["roslaunch", "mavros", "apm.launch", "fcu_url:=/dev/ttyAMA10:115200"]
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175

  orbslam3:
    build:
      context: ./orbslam3_ws
    container_name: orbslam3
    network_mode: host
    command: >
      bash -c "sleep 3 &&
      rosrun ORB_SLAM3 Mono
      /root/ORB_SLAM3/Vocabulary/ORBvoc.txt
      /root/catkin_ws/src/ORB_SLAM3/Examples/Monocular/TUM1.yaml"
    depends_on:
      - roscore
      - camera
      - mavros
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./orbslam3_ws/config:/root/orbslam3_config
      - ./orbslam3_ws/launch:/root/orbslam3_launch
      - /tmp/.X11-unix:/tmp/.X11-unix

  vinsfusion:
    build:
      context: ./imu_utils_ws
      dockerfile: vinsfusion_ws/Dockerfile
    container_name: vinsfusion
    network_mode: host
    command: >
      bash -c "sleep 3 && roslaunch vins vins_fusion.launch"
    depends_on:
      - roscore
      #- camera_stereo
      - mavros
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
    volumes:
      - ./vinsfusion_ws/config:/root/catkin_ws/src/VINS-Fusion/config

  imu_analyzer:
    build:
      context: ./allan_variance_ros_ws
      dockerfile: Dockerfile
    container_name: imu_analyzer
    depends_on:
      - roscore
      - mavros  # Depends on mavros to ensure the IMU topic is available
    network_mode: host
    #command: >
    #  bash -c "chmod +x /scripts/run_allan_variance.sh && 
    #  /scripts/run_allan_variance.sh"
    environment:
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
      - IMU_TOPIC=/mavros/imu/data_raw
      - DURATION=60
    volumes:
      - ./allan_variance_ros_ws/config:/config
      - ./allan_variance_ros_ws/imu_results:/data
      - ./allan_variance_ros_ws/scripts:/scripts

  ros_tools:
    build:
      context: ./ros_tools_ws
      dockerfile: Dockerfile
    container_name: ros_tools
    depends_on:
      - roscore
      - mavros #for IMU Topics
      - camera_mono #for Camera Topics
    network_mode: host
    image: ros-tools # Give the built image a name
    restart: "no" # This container doesn't need to run all the time
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1 # Often helps with stability for Qt apps like RQT
      - ROS_MASTER_URI=http://192.168.1.175:11311
      - ROS_IP=192.168.1.175
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /media/group7/USB-ESD:/storage
      - /home/group7/ros_bags:/root/ros_bags
      - /home/group7/.Xauthority:/root/.Xauthority:ro
    # --- Keep container running for exec ---
    stdin_open: true  # Equivalent to -i
    tty: true         # Equivalent to -t
